import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    'wiki/index',
    {
      type: 'category',
      label: 'Components',
      collapsed: true,
      items: [
        'wiki/components/overview',
        {
          type: 'category',
          label: 'Layout',
          collapsed: true,
          items: [
            'wiki/components/layout/card',
            'wiki/components/layout/card/accessibility',
            'wiki/components/layout/collapse/accessibility',
            'wiki/components/layout/container',
            'wiki/components/layout/grid',
          ],
        },
        {
          type: 'category',
          label: 'Inputs',
          collapsed: true,
          items: [
            'wiki/components/inputs/button',
            'wiki/components/inputs/button/accessibility',
            'wiki/components/inputs/checkbox',
            'wiki/components/inputs/checkbox/accessibility',
            'wiki/components/inputs/Input',
            'wiki/components/inputs/Select',
          ],
        },
        {
          type: 'category',
          label: 'Data Display',
          collapsed: true,
          items: [
            'wiki/components/data-display/avatar',
            'wiki/components/data-display/avatar/accessibility',
            'wiki/components/data-display/badge',
            'wiki/components/data-display/badge/accessibility',
            'wiki/components/data-display/list',
            'wiki/components/data-display/table',
            'wiki/components/data/table/accessibility',
          ],
        },
        {
          type: 'category',
          label: 'Navigation',
          collapsed: true,
          items: [
            'wiki/components/navigation/breadcrumb',
            'wiki/components/navigation/breadcrumb/accessibility',
            'wiki/components/navigation/menu',
            'wiki/components/navigation/pagination',
            'wiki/components/navigation/stepper',
            'wiki/components/navigation/tabs',
            'wiki/components/navigation/tabs/accessibility',
            'wiki/components/navigation/tabview',
          ],
        },
        {
          type: 'category',
          label: 'Feedback',
          collapsed: true,
          items: [
            'wiki/components/feedback/alert',
            'wiki/components/feedback/alert/accessibility',
            'wiki/components/feedback/progress',
            'wiki/components/feedback/spinner',
            'wiki/components/feedback/toast',
            'wiki/components/feedback/toast/accessibility',
          ],
        },
        {
          type: 'category',
          label: 'Overlay',
          collapsed: true,
          items: [
            'wiki/components/overlay/dialog',
            'wiki/components/overlay/dialog/accessibility',
            'wiki/components/overlay/drawer',
            'wiki/components/overlay/modal',
            'wiki/components/overlay/modal/accessibility',
            'wiki/components/overlay/popover',
            'wiki/components/overlay/tooltip',
          ],
        },
        {
          type: 'category',
          label: 'Forms',
          collapsed: true,
          items: [
            'wiki/components/forms/checkbox',
            'wiki/components/forms/colorpicker',
            'wiki/components/forms/datepicker/accessibility',
            'wiki/components/forms/fileupload',
            'wiki/components/forms/form-control',
            'wiki/components/forms/radio',
            'wiki/components/forms/radiogroup',
            'wiki/components/forms/select',
            'wiki/components/forms/slider',
            'wiki/components/forms/switch',
            'wiki/components/forms/textarea',
            'wiki/components/forms/timepicker',
          ],
        },
        {
          type: 'category',
          label: 'Disclosure',
          collapsed: true,
          items: [
            'wiki/components/disclosure/accordion',
            'wiki/components/disclosure/accordion/accessibility',
          ],
        },
        {
          type: 'category',
          label: 'Media',
          collapsed: true,
          items: [
            'wiki/components/media/carousel',
            'wiki/components/media/mediaplayer',
          ],
        },
        {
          type: 'category',
          label: 'Charts',
          collapsed: true,
          items: [
            'wiki/components/charts/line-chart',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'wiki/guides/quickstart',
        'wiki/guides/animations',
        'wiki/guides/form-validation',
        'wiki/guides/internationalization',
        'wiki/guides/migration-guide',
        'wiki/guides/mvp-development',
        'wiki/guides/reorganize',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      collapsed: true,
      items: [
        'wiki/development/guide',
        'wiki/development/roadmap',
        'wiki/development/Entwickler-Prompt',
        'wiki/development/build-analysis',
        'wiki/development/build-fix-guide',
        'wiki/development/build-troubleshooting',
        'wiki/development/changelog',
        'wiki/development/component-status',
        'wiki/development/contributing',
        'wiki/development/credits',
        'wiki/development/development-strategy',
        'wiki/development/documentation-strategy',
        'wiki/development/implementation-report',
        'wiki/development/local-installation',
        'wiki/development/performance-optimization',
        'wiki/development/project-guide',
        'wiki/development/release-plan-0.2.2',
        'wiki/development/security-compatibility',
        'wiki/development/status-report',
        'wiki/development/v0.2.1-release-notes',
        'wiki/development/v0.2.2-release-notes',
        {
          type: 'category',
          label: 'Releases',
          collapsed: true,
          items: [
            'wiki/development/releases/v0.2.1',
            'wiki/development/releases/v0.2.2',
          ],
        },
        {
          type: 'category',
          label: 'Roadmap',
          collapsed: true,
          items: [
            'wiki/development/roadmap/index',
            'wiki/development/roadmap/implementation-plan',
            'wiki/development/roadmap/step-by-step-guide',
            'wiki/development/roadmap/summary',
          ],
        },
        {
          type: 'category',
          label: 'Finanzierung',
          collapsed: true,
          items: [
            'wiki/development/Finanzierung/Budget&Ressourcen',
            'wiki/development/Finanzierung/Budgetplanung&Meilensteinen',
            'wiki/development/Finanzierung/Detailanalyse',
            'wiki/development/Finanzierung/Gesamt-MVP-Budgetuebersicht',
            'wiki/development/Finanzierung/Kalkulation-v0.2.2-0.3.0',
            'wiki/development/Finanzierung/Kalkulation-v0.2.2',
            'wiki/development/Finanzierung/Kalkulation-v0.3.0',
            'wiki/development/Finanzierung/Weiterentwicklung&Finanzierung',
            'wiki/development/Finanzierung/Zusammenfassung-Zeit&Kosten',
          ],
        },
        {
          type: 'category',
          label: 'Archive',
          collapsed: true,
          items: [
            'wiki/development/archive/v0.1/implementation-roadmap',
            'wiki/development/archive/v0.1/improvement-plan',
            'wiki/development/archive/v0.1/roadmap',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        'wiki/architecture/architecture-design',
        'wiki/architecture/build-process',
        'wiki/architecture/component-specification',
        'wiki/architecture/dependencies',
        'wiki/architecture/package-structure',
        'wiki/architecture/requirements-analysis',
        'wiki/architecture/technical-requirements',
      ],
    },
    {
      type: 'category',
      label: 'Guidelines',
      collapsed: true,
      items: [
        'wiki/guidelines/accessibility',
        'wiki/guidelines/best-practices',
        'wiki/guidelines/coding-standards',
        'wiki/guidelines/component-structure',
        'wiki/guidelines/testing-strategy',
        'wiki/guidelines/theming/index',
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      collapsed: true,
      items: [
        'wiki/testing/test-strategy',
        'wiki/testing/a11y-test-plan',
        'wiki/testing/a11y-test-template',
        'wiki/testing/accessibility-testing',
        'wiki/testing/component-prioritization',
        'wiki/testing/e2e-testing',
        'wiki/testing/test-coverage-report',
        'wiki/testing/testing-standards',
        {
          type: 'category',
          label: 'Implementation',
          collapsed: true,
          items: [
            'wiki/testing/implementation/accessibility-tests',
            'wiki/testing/implementation/automated-a11y-tests',
            'wiki/testing/implementation/component-tests',
            'wiki/testing/implementation/snapshot-tests',
          ],
        },
        {
          type: 'category',
          label: 'Presentation',
          collapsed: true,
          items: [
            'wiki/testing/presentation/testplan-implementation',
          ],
        },
        {
          type: 'category',
          label: 'Testplan',
          collapsed: true,
          items: [
            'wiki/testing/testplan/01-Testplan-Uebersicht',
            'wiki/testing/testplan/02-Testinfrastruktur',
            'wiki/testing/testplan/03-Unit-Tests',
            'wiki/testing/testplan/04-Integrationstests',
            'wiki/testing/testplan/05-Spezielle-Komponententests',
            'wiki/testing/testplan/06-Visuelle-Tests',
            'wiki/testing/testplan/07-Browserkompatibilitaetstests',
            'wiki/testing/testplan/08-CI-CD-Integration',
            'wiki/testing/testplan/09-Implementierungsplan',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: true,
      items: [
        'wiki/examples/form-examples',
        'wiki/examples/form-validation-examples',
        'wiki/examples/layout-examples',
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: true,
      items: [
        'wiki/api/reference',
      ],
    },
    {
      type: 'category',
      label: 'Accessibility',
      collapsed: true,
      items: [
        'wiki/accessibility/a11y-components',
        'wiki/accessibility/component-status',
        {
          type: 'category',
          label: 'Components',
          collapsed: true,
          items: [
            'wiki/accessibility/components/carousel',
            'wiki/accessibility/components/colorpicker',
            'wiki/accessibility/components/drawer',
            'wiki/accessibility/components/dropdown',
            'wiki/accessibility/components/fade',
            'wiki/accessibility/components/fileupload',
            'wiki/accessibility/components/flex',
            'wiki/accessibility/components/form',
            'wiki/accessibility/components/formcontrol',
            'wiki/accessibility/components/formfield',
            'wiki/accessibility/components/input',
            'wiki/accessibility/components/languageswitcher',
            'wiki/accessibility/components/list',
            'wiki/accessibility/components/mediaplayer',
            'wiki/accessibility/components/menu',
            'wiki/accessibility/components/pagination',
            'wiki/accessibility/components/popover',
            'wiki/accessibility/components/progressbar',
            'wiki/accessibility/components/radio',
            'wiki/accessibility/components/select',
            'wiki/accessibility/components/skeleton',
            'wiki/accessibility/components/slide',
            'wiki/accessibility/components/slider',
            'wiki/accessibility/components/spinner',
            'wiki/accessibility/components/stepper',
            'wiki/accessibility/components/switch',
            'wiki/accessibility/components/tabview',
            'wiki/accessibility/components/textarea',
            'wiki/accessibility/components/timepicker',
            'wiki/accessibility/components/zoom',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Voice Control',
          collapsed: true,
          items: [
            'wiki/features/voice-control/component-integration',
            'wiki/features/voice-control/implementation-guide',
            'wiki/features/voice-control/tensorflow-integration',
            'wiki/features/voice-control/voice-control-architecture',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Improvement Plan',
      collapsed: true,
      items: [
        'wiki/improvement-plan/button-component',
        'wiki/improvement-plan/phase2-accessibility',
      ],
    },
  ],
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial Basics',
      collapsed: false,
      items: [
        'tutorial-basics/create-a-document',
      ],
    },
  ],
};

export default sidebars;