import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [{ type: 'autogenerated', dirName: '.' }],
  guideSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
