import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
    {
      type: 'autogenerated',
      dirName: 'components',
    },
    {
      type: 'autogenerated',
      dirName: 'development',
    },
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
    {
      type: 'autogenerated',
      dirName: 'guidelines',
    },
    {
      type: 'autogenerated',
      dirName: 'testing',
    },
    {
      type: 'autogenerated',
      dirName: 'features',
    },
    {
      type: 'autogenerated',
      dirName: 'examples',
    },
    {
      type: 'autogenerated',
      dirName: 'packages',
    },
    {
      type: 'autogenerated',
      dirName: 'accessibility',
    },
    {
      type: 'autogenerated',
      dirName: 'styling',
    },
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
  guideSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
