// Mock-Daten für die TrendingTopics-Komponente
export const mockTrendingTopics = [
  {
    id: '1',
    name: 'Künstliche Intelligenz',
    description: 'Fortschritte und Entwicklungen im Bereich der künstlichen Intelligenz und maschinellen Lernens.',
    category: 'Technologie',
    mentionCount: 1245,
    change: 15.3,
    isNew: false,
    relatedTopics: ['Machine Learning', 'Deep Learning', 'Neural Networks', 'AI Ethics'],
    relatedContent: [
      {
        id: 'c1',
        title: 'Die Zukunft der KI in der Medizin',
        url: '#',
        type: 'article',
        thumbnail: 'https://via.placeholder.com/100',
      },
      {
        id: 'c2',
        title: 'Ethische Fragen bei KI-Entscheidungen',
        url: '#',
        type: 'video',
        thumbnail: 'https://via.placeholder.com/100',
      },
    ],
  },
  {
    id: '2',
    name: 'Blockchain-Technologie',
    description: 'Dezentrale Systeme, Kryptowährungen und Blockchain-Anwendungen.',
    category: 'Technologie',
    mentionCount: 987,
    change: 8.7,
    isNew: false,
    relatedTopics: ['Kryptowährungen', 'Smart Contracts', 'DeFi', 'NFTs'],
    relatedContent: [
      {
        id: 'c3',
        title: 'Blockchain jenseits von Kryptowährungen',
        url: '#',
        type: 'article',
        thumbnail: 'https://via.placeholder.com/100',
      },
    ],
  },
  {
    id: '3',
    name: 'Quantencomputing',
    description: 'Fortschritte in der Quantencomputertechnologie und deren Anwendungen.',
    category: 'Wissenschaft',
    mentionCount: 654,
    change: 23.5,
    isNew: true,
    relatedTopics: ['Quantenphysik', 'Quantenkryptographie', 'Quantenalgorithmen'],
    relatedContent: [
      {
        id: 'c4',
        title: 'Quantencomputer: Die nächste Revolution?',
        url: '#',
        type: 'article',
        thumbnail: 'https://via.placeholder.com/100',
      },
    ],
  },
  {
    id: '4',
    name: 'Klimawandel',
    description: 'Diskussionen über Klimawandel, Umweltschutz und nachhaltige Entwicklung.',
    category: 'Wissenschaft',
    mentionCount: 1432,
    change: 5.2,
    isNew: false,
    relatedTopics: ['Nachhaltigkeit', 'Erneuerbare Energien', 'CO2-Reduktion'],
    relatedContent: [
      {
        id: 'c5',
        title: 'Innovative Lösungen gegen den Klimawandel',
        url: '#',
        type: 'article',
        thumbnail: 'https://via.placeholder.com/100',
      },
    ],
  },
  {
    id: '5',
    name: 'Digitale Kunst',
    description: 'Neue Formen digitaler Kunst und deren Einfluss auf die Kunstwelt.',
    category: 'Kultur',
    mentionCount: 543,
    change: 45.8,
    isNew: true,
    relatedTopics: ['NFTs', 'Digitale Galerien', 'Kryptokunst'],
    relatedContent: [
      {
        id: 'c6',
        title: 'Die Revolution der digitalen Kunst',
        url: '#',
        type: 'video',
        thumbnail: 'https://via.placeholder.com/100',
      },
    ],
  },
];

// Mock-Daten für die EngagementScore-Komponente
export const mockEngagementData = {
  metrics: [
    {
      name: 'Aufrufe',
      value: 12500,
      weight: 0.2,
      description: 'Anzahl der Aufrufe des Inhalts',
      benchmark: 8000,
      higherIsBetter: true,
    },
    {
      name: 'Durchschnittliche Verweildauer',
      value: 245,
      weight: 0.25,
      description: 'Durchschnittliche Zeit in Sekunden, die Nutzer mit dem Inhalt verbringen',
      benchmark: 180,
      higherIsBetter: true,
    },
    {
      name: 'Interaktionsrate',
      value: 8.7,
      weight: 0.3,
      description: 'Prozentsatz der Nutzer, die mit dem Inhalt interagieren (Likes, Kommentare, Shares)',
      benchmark: 5.2,
      higherIsBetter: true,
    },
    {
      name: 'Absprungrate',
      value: 25.3,
      weight: 0.15,
      description: 'Prozentsatz der Nutzer, die den Inhalt sofort verlassen',
      benchmark: 35.8,
      higherIsBetter: false,
    },
    {
      name: 'Konversionsrate',
      value: 3.2,
      weight: 0.1,
      description: 'Prozentsatz der Nutzer, die eine gewünschte Aktion ausführen',
      benchmark: 2.5,
      higherIsBetter: true,
    },
  ],
  recommendations: [
    'Fügen Sie mehr visuelle Elemente hinzu, um die Aufmerksamkeit der Nutzer zu erhöhen.',
    'Optimieren Sie die Ladezeit des Inhalts, um die Absprungrate zu reduzieren.',
    'Integrieren Sie interaktive Elemente, um die Nutzerinteraktion zu fördern.',
    'Verbessern Sie den Call-to-Action, um die Konversionsrate zu steigern.',
  ],
};