name: Accessibility Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  # Ermöglicht manuelle Ausführung des Workflows
  workflow_dispatch:

jobs:
  a11y-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run accessibility tests
        run: npm run test:a11y
      
      - name: Generate accessibility report
        run: npm run test:a11y:report
      
      - name: Upload accessibility report
        uses: actions/upload-artifact@v3
        with:
          name: a11y-report
          path: a11y-report/
          retention-days: 30
      
      - name: Check for critical accessibility issues
        run: |
          if grep -q '"critical": [^0]' a11y-report/results.json; then
            echo "Critical accessibility issues found!"
            exit 1
          fi