name: Reusable Docker Build Workflow

on:
  workflow_call:
    inputs:
      registry:
        description: 'Container registry to push to'
        type: string
        required: false
        default: 'ghcr.io'
      image-name:
        description: 'Name of the Docker image'
        type: string
        required: true
      dockerfile-path:
        description: 'Path to the Dockerfile'
        type: string
        required: false
        default: './Dockerfile'
      build-args:
        description: 'JSON string of build arguments'
        type: string
        required: false
        default: '{}'
      push:
        description: 'Whether to push the image'
        type: boolean
        required: false
        default: true
      platforms:
        description: 'Platforms to build for'
        type: string
        required: false
        default: 'linux/amd64,linux/arm64'
    secrets:
      REGISTRY_USERNAME:
        required: false
        description: 'Username for container registry'
      REGISTRY_PASSWORD:
        required: false
        description: 'Password for container registry'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        if: inputs.push == true && secrets.REGISTRY_USERNAME != ''
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image-name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile-path }}
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max