name: Fix GitHub Pages 404 Error

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Grund fuer die Behebung des 404-Fehlers'
        required: false
        default: 'Behebung des 404-Fehlers auf GitHub Pages'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  fix-pages:
    name: Fix GitHub Pages 404 Error
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
      
      - name: Create and push empty gh-pages branch
        run: |
          git checkout --orphan temp-gh-pages
          git rm -rf .
          echo "# GitHub Pages" > README.md
          echo "This branch contains the built documentation." >> README.md
          touch .nojekyll
          git add README.md .nojekyll
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Reset GitHub Pages"
          git branch -D gh-pages || true
          git branch -m gh-pages
          git push -f origin gh-pages
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: docs/package-lock.json
      
      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main
      
      - name: Install dependencies
        working-directory: docs
        run: |
          rm -rf node_modules package-lock.json
          npm install @docusaurus/logger
          npm install
      
      - name: Build website
        working-directory: docs
        run: npm run build
      
      - name: Create .nojekyll file
        working-directory: docs
        run: touch build/.nojekyll
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com