name: Reset GitHub Pages Settings

on:
  # Automatische Ausfuehrung bei Fehlern im Docusaurus-Deploy-Workflow
  workflow_run:
    workflows: ["Deploy Docusaurus to GitHub Pages"]
    types:
      - failed
    branches:
      - main
  # Ermoeglicht auch manuelle Ausfuehrung
  workflow_dispatch:
    inputs:
      reason:
        description: 'Grund fuer das Zuruecksetzen der GitHub Pages-Einstellungen'
        required: false
        default: 'Behebung von Problemen mit der GitHub Pages-Bereitstellung'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  reset-pages:
    name: Reset GitHub Pages Settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Create empty gh-pages branch
        run: |
          git checkout --orphan temp-gh-pages
          git rm -rf .
          echo "# GitHub Pages" > README.md
          echo "This branch contains the built documentation." >> README.md
          touch .nojekyll
          git add README.md .nojekyll
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Reset GitHub Pages"
          git branch -D gh-pages || true
          git branch -m gh-pages
          git push -f origin gh-pages